# Generated by Django 5.0.2 on 2024-03-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryModels',
        ),
    ]
