# Generated by Django 5.0.2 on 2024-04-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_game', '0003_scoremodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreModels',
        ),
    ]
